// GENERATED FILE. Do not edit by hand.
// Source: public/sp16.pdf (outline/bookmarks)

import type { SpClause } from "./sp-data";

export const SP16_CLAUSES: SpClause[] = [
  {
    id: "0.03",
    title: "0.03 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.04",
    title: "0.04 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.05",
    title: "0.05 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.14",
    title: "0.14 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.41",
    title: "0.41 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.45",
    title: "0.45 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.65",
    title: "0.65 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.75",
    title: "0.75 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "0.90",
    title: "0.90 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1",
    title: "1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.0",
    title: "1.0 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.1",
    title: "1.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.2",
    title: "1.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.05",
    title: "1.05 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.6",
    title: "1.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.10",
    title: "1.10 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.15",
    title: "1.15 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.20",
    title: "1.20 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.25",
    title: "1.25 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.35",
    title: "1.35 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.050",
    title: "1.050 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.70",
    title: "1.70 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "1.100",
    title: "1.100 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "2",
    title: "2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "3",
    title: "3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4",
    title: "4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.1",
    title: "4.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.1.1",
    title: "4.1.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.1.2",
    title: "4.1.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.1.3",
    title: "4.1.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2",
    title: "4.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.1",
    title: "4.2.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.2",
    title: "4.2.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.3",
    title: "4.2.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.4",
    title: "4.2.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.5",
    title: "4.2.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.6",
    title: "4.2.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.7",
    title: "4.2.7 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.2.8",
    title: "4.2.8 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3",
    title: "4.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3.1",
    title: "4.3.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3.2",
    title: "4.3.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3.3",
    title: "4.3.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3.4",
    title: "4.3.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "4.3.5",
    title: "4.3.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5",
    title: "5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.1",
    title: "5.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.2",
    title: "5.2 (каркас)",
    summary: "",
    calculators: [],
    formulaBlockIds: ["rect-area","rect-inertia","rect-section-modulus"],
  },
  {
    id: "5.3",
    title: "5.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.4",
    title: "5.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.5",
    title: "5.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.6",
    title: "5.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.7",
    title: "5.7 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.8",
    title: "5.8 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.9",
    title: "5.9 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.10",
    title: "5.10 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "5.11",
    title: "5.11 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6",
    title: "6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.1",
    title: "6.1 (каркас)",
    summary: "",
    calculators: [],
    formulaBlockIds: ["steel-axial-stress","utilization"],
  },
  {
    id: "6.2",
    title: "6.2 (каркас)",
    summary: "",
    calculators: [],
    formulaBlockIds: ["steel-shear-stress","utilization"],
  },
  {
    id: "6.3",
    title: "6.3 (каркас)",
    summary: "",
    calculators: [],
    formulaBlockIds: ["steel-bending-stress","utilization"],
  },
  {
    id: "6.4",
    title: "6.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.5",
    title: "6.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.6",
    title: "6.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.7",
    title: "6.7 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.8",
    title: "6.8 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "6.9",
    title: "6.9 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7",
    title: "7 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1",
    title: "7.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1.1",
    title: "7.1.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1.2",
    title: "7.1.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1.4",
    title: "7.1.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1.5",
    title: "7.1.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.1.6",
    title: "7.1.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2",
    title: "7.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2.1",
    title: "7.2.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2.2",
    title: "7.2.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2.3",
    title: "7.2.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2.4",
    title: "7.2.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.2.5",
    title: "7.2.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "7.3",
    title: "7.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8",
    title: "8 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.1",
    title: "8.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.2",
    title: "8.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.3",
    title: "8.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.4",
    title: "8.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.5",
    title: "8.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "8.6",
    title: "8.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "9",
    title: "9 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "9.1",
    title: "9.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "9.2",
    title: "9.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "9.3",
    title: "9.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "9.4",
    title: "9.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "10",
    title: "10 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "10.1",
    title: "10.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "10.2",
    title: "10.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "10.3",
    title: "10.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "10.4",
    title: "10.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "11",
    title: "11 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "11.1",
    title: "11.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "11.2",
    title: "11.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "12",
    title: "12 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "12.1",
    title: "12.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "12.2",
    title: "12.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "12.9",
    title: "12.9 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "13",
    title: "13 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "14",
    title: "14 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "14.1",
    title: "14.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "14.2",
    title: "14.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "14.3",
    title: "14.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "14.4",
    title: "14.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15",
    title: "15 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.1",
    title: "15.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.2",
    title: "15.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.3",
    title: "15.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.4",
    title: "15.4 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.5",
    title: "15.5 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.6",
    title: "15.6 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.7",
    title: "15.7 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.8",
    title: "15.8 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.9",
    title: "15.9 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "15.12",
    title: "15.12 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "16",
    title: "16 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "17",
    title: "17 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "18",
    title: "18 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "18.1",
    title: "18.1 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "18.2",
    title: "18.2 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "18.3",
    title: "18.3 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "35",
    title: "35 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "40",
    title: "40 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "48",
    title: "48 (каркас)",
    summary: "",
    calculators: [],
  },
  {
    id: "60",
    title: "60 (каркас)",
    summary: "",
    calculators: [],
  },
];
